### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by ararslan** [JuliaMath/SpecialFunctions.jl#1]
Based on @tkelman's comment on JuliaLang/openspecfun#44, it sounds like @nolta was in the midst of porting the Fortran functions to pure Julia, after which I assume they'd be removed entirely from SpecialFunctions. Is that true?

It seems to me that this project could be made much simpler by using BinDeps with openspecfun as a binary dependency, thereby excluding the Fortran code from the repo and instead relying on openspecfun, which appears to be well maintained. That also avoids having to reinvent the wheel in terms of porting everything to Julia, unless that was a central goal.

Edit: Using openspecfun would also give us the Faddeeva functions as well as amos.

**Comment by tkelman** [comment]
This Fortran code is from openspecfun. The point of this would be to finish cleaning this up, add tests, docs, etc to the pure Julia code then verify that it's close enough in performance to the Fortran in openspecfun that we could remove openspecfun as a build dependency of Julia.

I don't think Faddeeva is all that widely used or important, but if it is we could translate some of it to Julia or use BinDeps only for Faddeeva.

**Comment by ararslan** [comment]
Okay, that makes sense. Thanks for the explanation!

**Comment by ararslan** [comment]
@tkelman Hm, but if SpecialFunctions is being separated out from Base, why couldn't openspecfun be a build dependency for this package once it's removed from Base? I guess I'm failing to see why porting it to Julia is necessary.

**Comment by tkelman** [comment]
Fortran dependencies are kind of a pain, and since most of the porting has already been done and performance was reported to be good, removing the trouble of binaries (and I disagree with "well maintained," nobody touches that fortran code) in favor of a pure-Julia replacement is worth the small amount of cleanup that would be needed to finish up here. It's not urgent, but openspecfun doesn't really need to exist long-term. This would be replacing the largest and most inconvenient part of it, the Fortran code.

**Comment by ararslan** [comment]
Out of curiosity, what makes Fortran dependencies a pain? Does gfortran do name mangling or something?

**Comment by tkelman** [comment]
gfortran's name mangling is relatively simple to predict, but it forces you to link to gcc runtimes which isn't the platform compiler anywhere other than Linux (and not even every distribution any more), gfortran isn't installed everywhere and it's GPL licensed, Intel's Fortran compiler is better but not free and not always compatible, etc. And all the annoying distribution headaches you inherit with C libraries, just worse.

**Comment by ararslan** [comment]
Port to Julia it is, then!

**Comment by ararslan** [comment]
@tkelman Should we have GitHub separate this as its own repo rather than keep it as a fork of nolta's? If nothing else it'd be nice to be able to search, which isn't possible for forks for whatever reason.

**Comment by tkelman** [comment]
I guess we could do that. Could also delete this one, create a new empty repo then git push a clone into it. That wouldn't show up as a fork but would delete this issue.

**Comment by simonbyrne** [comment]
I think you can also email support, and they can switch it to a normal repository.

**Comment by ararslan** [comment]
@simonbyrne Yeah, that's what I meant. That seems like a good idea to me.

I'd also be fine with @tkelman's suggestion to push to a new repo. I personally wouldn't mind this issue being erased from history though I suppose it's nice to have for backstory/reference/etc.

**Comment by ararslan** [comment]
I'd be in favor of having support convert this fork to a normal repo. If you guys agree then I can go ahead and email them, otherwise I'm fine with whatever.

**Comment by tkelman** [comment]
I don't mind if you want to do that.

**Comment by ararslan** [comment]
The deed is done.
