### ISSUE TITLE
Is this a home for special function implementations in Julia?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaMath/SpecialFunctions.jl#112]
@MikaelSlevinsky Has an implementation of Gauss Hypergeometric function  ₂F₁ currently living in SingularIntegralEquations.jl:

https://github.com/JuliaApproximation/SingularIntegralEquations.jl/tree/master/src/HypergeometricFunctions

It would be nice to move this out so that others can use it. Is this the right home for this? If so, I can make a PR.

Something to consider is the level of reliability of special functions. One can either take the Mathematica approach of "it's better to give the wrong answer than no answer at all" or a more restrictive "it's better to give no answer at all than the right answer if unsure". The latter seems safer, but in the case of Hypergeometric functions the number of parameters makes this burdensome. 

It might make sense to have two packages, this one and an UntestedSpecialFunctions.jl.

**Comment by jwscook** [comment]
Hi SpecialFunction devs. Is there any consensus on this issue? There's growing momentum to move Hypergeometric functions out of SingularIntegralEquations, and it'd be nice to put them here if you'll take them?

**Comment by stevengj** [comment]
I think it would be reasonable to put them here.

**Comment by luca-aki** [comment]
I was working with some hypergeom functions and later found this issue. Any reason for no momentum to implement/move them in SpecialFunctions.jl ?

**Comment by dlfivefifty** [comment]
Note that development has moved to https://github.com/JuliaApproximation/HypergeometricFunctions.jl

I think it would be preferable to keep it a separate package while it's still experimental.

@jwscook I see that you tagged a pre-release. Should we tag a release 0.0.1 so its in METADATA?

**Comment by jwscook** [comment]
This got pushed to the bottom of the pile. I have the vague feeling that the ball is in attobot's court. I'll check later.

**Comment by dlfivefifty** [comment]
I believe attobot needs a version of at least 0.0.1 to be triggered.

**Comment by musm** [comment]
Consensus is that PRs with tests are welcome so that others can enjoy using these functions.

**Comment by dlfivefifty** [comment]
I'm going to close this in favour of the new issue with a concrete proposal.
