### ISSUE TITLE
Inclusion of base/special functions

### ISSUE THREAD

**Issue by ararslan** [JuliaMath/SpecialFunctions.jl#12]
In https://github.com/JuliaLang/julia/pull/17130#issuecomment-228730978, @tkelman mentioned that everything in base/special would be moved into this package. I wanted to clarify a few things and figured that here would be a better place to do that than on Katharine's PR.

Currently this project is only including the Fortran functions defined in AMOS, whereas base/special also includes things from Faddeeva (e.g. `erf`) and OpenLibm (e.g. `gamma`). So this project will inherit Faddeeva and OpenLibm stuff as well? The OpenLibm dependency is a nonissue since it's included with Julia anyway, but Faddeeva is more Fortran and I assume that once base/special is migrated out of Base, Faddeeva will no longer be included with Julia. That means we either have to do the Fortran -> Julia translation thing, rewrite the functions in pure Julia, or introduce a Fortran binary dependency. Right?

**Comment by ararslan** [comment]
Surely we can't be taking *everything* in base/special. Not having `log` in Base would be heresy.

**Comment by tkelman** [comment]
I think Faddeeva's actually C++, not Fortran? We can certainly leave `log` in Base, but we can also do one thing at a time. Airy and Bessel can probably move here first.

**Comment by ararslan** [comment]
Huh, could have sworn it was Fortran but it looks like you're right, it's C++. And Julia's own Steven G. Johnson wrote it, no less! :smile: 

Yeah, I figured we wouldn't do all of it at once. Bessel and airy sounds like a good place to start. I'd still like to rewrite (or at least refactor) the translated Julia code from AMOS to be more idiomatic, it just requires the mental gymnastics of following `goto`s.

Hopefully moving the tests from Base will help increase the currently abysmal coverage.

**Comment by ararslan** [comment]
I'll start a checklist here of stuff to copy over based on my understanding of the plan. Feel free to add/subtract at will.

- [x] Airy
- [x] Bessel
- [ ] Error functions
- [ ] Gamma, digamma, et al.
