### ISSUE TITLE
beta(-n,n) gives NaN, when n is an integer

### ISSUE THREAD

**Issue by QMrpy** [JuliaMath/SpecialFunctions.jl#149]
Beta function at negative integer argument x=n should give ((-1)^n)/n, but instead it gives NaN.The evaluation at negative integers must be done by taking limits close to -n, where the pole at negative integers cancels out

**Comment by Peiffap** [comment]
Some work on this was done in https://github.com/JuliaLang/julia/pull/14349

**Comment by simonbyrne** [comment]
See also discussion in https://github.com/JuliaLang/julia/issues/14256. Would be also good to address cancellation issues when arguments have large difference in magnitudes (see https://github.com/JuliaLang/julia/issues/4301#issuecomment-24736245).

Several utility functions were added in #165 which might be reused for this.
