### ISSUE TITLE
Bump Julia version requirement?

### ISSUE THREAD

**Issue by ararslan** [JuliaMath/SpecialFunctions.jl#15]
I'd like to propose that we bump the Julia version requirement from the current 0.4- to 0.5-, and in doing so also remove the `@vectorize_*` calls in favor of `.` broadcasts. These will likely be deprecated in Base soon anyway, given the move away from implicit vectorization.

Since this package isn't registered I figured this wouldn't be too controversial, though I could certainly be wrong. Thoughts?

cc @tkelman @simonbyrne

**Comment by tkelman** [comment]
depends what packages would need to depend on this one after we eventually remove these from base. probably okay since that will be 0.6 at the earliest.

**Comment by ararslan** [comment]
I think which packages will depend on this one depends on the scope of the removal from base (ref #12). If `gamma` moves out of base, the number of packages that need this will be much higher. One example that comes to mind is JuliaStats/Distributions.jl. And if error functions are moved out, JuliaStats/StatsBase.jl will need this too.

**Comment by tkelman** [comment]
I think `gamma` and `erf` could stay in base for a little longer than bessel, airy, and higher-order gamma derivatives

**Comment by ararslan** [comment]
Sounds like a good plan.
