### ISSUE TITLE
Is SpecialFunctions.jl compatible with PackegeCompiler.jl?

### ISSUE THREAD

**Issue by cbadillac** [JuliaMath/SpecialFunctions.jl#150]
I've executed a binary generated with PackageCompiler.jl but when it run in another PC, this can't find the package SpecialFunctions.jl, because the path that use to find it is from the PC where was compiled. 

![image](https://user-images.githubusercontent.com/7343291/54886168-97fa4180-4e63-11e9-8616-d5f5369ed74f.png)

Please your support.
Thanks

**Comment by ararslan** [comment]
I think this is a question for the PackageCompiler folks, so this issue should be opened on that repository instead. I don't know how it handles packages with external binary dependencies.
