### ISSUE TITLE
lgamma() wrong complex result with real argument

### ISSUE THREAD

**Issue by hsgg** [JuliaMath/SpecialFunctions.jl#154]
Consider `lgamma()` with real and complex arguments:

    julia> lgamma(-4.5)
    -2.813084081769316

    julia> lgamma(-4.5+0im)
    -2.813084081769315 - 15.707963267948966im

I assume the first one is wrong, since exponentiation does not reproduce `gamma(-4.5)` by a sign error. The latter works and agrees with `Mathematica` and `mpmath` (except for the last real digit, then the first expression ending in `...316` is more precise!).

I would expect `lgamma(-4.5)` to have the same behavior as `sqrt(-4.5)`, which gives a `DomainError`.

**Comment by simonbyrne** [comment]
This is consistent with the [definition of `lgamma`](https://github.com/JuliaMath/SpecialFunctions.jl/blob/fbd22a03a505f98e7aa75b96e8a705c89bac0f15/src/gamma.jl#L599-L606):

>   lgamma(x)
> 
>   Compute the logarithm of the absolute value of gamma for Real x, while for
>   Complex x compute the principal branch cut of the logarithm of gamma(x)
>   (defined for negative real(x) by analytic continuation from positive
>   real(x)).

I do agree that this definition goes against the general idea that mathematical functions should be defined consistently across types, but I suspect the `lgamma` behaviour is inherited from C, where the `lgamma`/`lgammaf`/`lgammal` functions are defined as:

> The lgamma functions compute the natural logarithm of the absolute value of gamma of x. A range error occurs if x is too large. A pole error may occur if x is a negative integer or zero.

(the complex version, `clgamma`, isn't defined but the name is reserved for future use).

One option would be to split them into functions with more descriptive names, e.g. `logabsgamma` and `loggamma` (the former has precedence with `logabsdet` in the LinearAlgebra stdlib).

**Comment by hsgg** [comment]
Ah, I should have read the documentation... Thank you for the explanation!

I like the option of giving descriptive names `logabsgamma` and `loggamma`. That seems very intuitive.

**Comment by andreasnoack** [comment]
I support the renaming.

**Comment by Sumegh-git** [comment]
Regarding `deprecation` of the `lgamma`, we must then rename the current `lgamma` with `logabsgamma` and write seperately for `loggamma` which calls `lgamma_r`. Then we can use `@deprecate` macro to redirect all `lgamma` calls to `logabsgamma`.
What is everyone's views on this?

**Comment by hsgg** [comment]
In the same spirit, should `lbeta` be renamed to `logabsbeta`? And `lbinomial` to `logabsbinomial`?

**Comment by simonbyrne** [comment]
> Then we can use `@deprecate` macro to redirect all `lgamma` calls to `logabsgamma`.

Sort of: you would want
```
@deprecate lgamma(x::Real) logabsgamma(x)
@deprecate lgamma(x::Complex) loggamma(x)

**Comment by simonbyrne** [comment]
See #156.
