### ISSUE TITLE
Gamma function does not show up  in the documentation

### ISSUE THREAD

**Issue by OvidiusCicero** [JuliaMath/SpecialFunctions.jl#157]
<http://juliamath.github.io/SpecialFunctions.jl/stable/> does not mention the `gamma`function although it exists and has a docstring and also appears in <https://github.com/JuliaMath/SpecialFunctions.jl/blob/master/docs/src/special.md>

**Comment by simonbyrne** [comment]
Was fixed by #114: just no release has been tagged since.

**Comment by OvidiusCicero** [comment]
Ah okay. I was puzzled because it seemed like “this should not be the output”. Thanks!
