### ISSUE TITLE
Port "Improve the Type consistency of Special Functions" pull request here

### ISSUE THREAD

**Issue by tkelman** [JuliaMath/SpecialFunctions.jl#17]
https://github.com/JuliaLang/julia/pull/18584, would be nice to preserve @oxinabox's authorship as well

**Comment by tkelman** [comment]
https://gist.github.com/84de6e5d71d989c549cb20671929302c

**Comment by ararslan** [comment]
Awesome, thanks for the diff! That's incredibly helpful.

**Comment by ararslan** [comment]
There's some stuff in there that touches sysimg.jl. Is that still relevant for Base?

**Comment by tkelman** [comment]
No, those would be squashed out - see https://gist.github.com/7c7c059b7bbac9f8a9e0a42a461ae179 for combined version

**Comment by ararslan** [comment]
PERFECT THANK YOU

**Comment by tkelman** [comment]
https://github.com/JuliaLang/julia/pull/18584.patch
https://github.com/JuliaLang/julia/pull/18584.diff
(though if the source branch changes then I'm not sure if github might do something funky, hence why I backed up to a gist)
