### ISSUE TITLE
Pull binaries from Yggdrasil now that openspecfun is in

### ISSUE THREAD

**Issue by ViralBShah** [JuliaMath/SpecialFunctions.jl#179]
The [openspecfun builder](https://github.com/JuliaPackaging/Yggdrasil/pull/34) is now available in Yggdrasil and we have [openspecfun binaries](https://github.com/JuliaPackaging/Yggdrasil/releases/tag/OpenSpecFun-v0.5.3%2B0)

How do we generate the `build_info` and move the downloads over?

**Comment by ViralBShah** [comment]
@ararslan You seemed to have helped with this earlier - pinging you in case you know the next steps.

**Comment by ararslan** [comment]
#180
