### ISSUE TITLE
0.8 update and loggamma

### ISSUE THREAD

**Issue by denizyuret** [JuliaMath/SpecialFunctions.jl#182]
I have SpecialFunctions as a Knet dependency. During the last update to 0.8 I saw lgamma was deprecated and modified my code accordingly. However after I released it a number of people wrote saying their Pkg.update() did not increase SpecialFunctions to 0.8. Any idea why this might be? Relevant Knet issue: https://github.com/denizyuret/Knet.jl/issues/486

**Comment by ederekGitHub** [comment]
Hi Deniz - first, many thanks for all your efforts! Just had this issue and here are complete details hopefully of help. 
System: Win10 / Julia1.2 / GeForce GTX 960M (Compute Capability: 5.0)
Your post about lgamma / loggamma and SpecialFunctions was the clue to resolve this:
(https://github.com/denizyuret/Knet.jl/issues/486). 
First, found the dependencies blocking updates to SpecialFunctions (was at v0.7.2):
Tried installing SpecialFunctions and specifiying the version (0.8). Note error message showing depencies for Distributions and Bridge:
(v1.2) pkg> add SpecialFunctions@0.8.0
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package SpecialFunctions [276daf66]:
 SpecialFunctions [276daf66] log:
 ├─possible versions are: [0.0.1, 0.1.0-0.1.1, 0.2.0, 0.3.0-0.3.8, 0.4.0, 0.5.0, 0.6.0, 0.7.0-0.7.2, 0.8.0] or uninstalled ├─restricted to versions 0.8.0 by an explicit requirement, leaving only versions 0.8.0
 └─restricted by compatibility requirements with Distributions [31c24e10] to versions: 0.7.0-0.7.2 — no versions left
   └─Distributions [31c24e10] log:
     ├─possible versions are:  ...
     ├─restricted to versions * by Bridge [2d3116d5], leaving only versions [0.1.0-0.1.4, ...
     │   └─Bridge [2d3116d5] is fixed to version 0.10.0
     └─restricted to versions 0.21.1 by an explicit requirement, leaving only versions 0.21.1
So:
(v1.2) pkg> rm Distributions
(v1.2) pkg> rm Bridge
(v1.2) pkg> add SpecialFunctions@0.8.0

Not sure if needed, but pinned SpecialFunctions to v0.8:
using Pkg
Pkg.pin(PackageSpec(name="SpecialFunctions", version="0.8.0"))

In parallel with resolving SpecialFunctions, was also getting rest of install correct. Added Visual Studio and fixed issues with lib (Knet.libknet8 = "") updated to properly link to (Knet.libknet8 = "C:\\Users\\ ... \\deps\\libknet8"). Also with a missing .h file, needed to add the Windows10 SDK in VS installer checkbox options, had only started wtih C++ Core Desktop Features. Installed cuDNN (https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html#installdriver-windows - didn't do step 4.3.5 "Include cudnn.lib in your Visual Studio project"). Upgraded nvidia driver. Rebooted system. 

Add Distributions package back, which worked:
(v1.2) pkg> add Distributions
 - adds Distributions v0.19.2 
(v1.2) pkg> build Distributions
(v1.2) pkg> test Distributions
Note this interesting warning message that appeared during test:
┌ Warning: `lgamma(x::Real)` is deprecated, use `(logabsgamma(x))[1]` instead.
│   caller = lstirling_asym(::BigFloat) at misc.jl:56
└ @ StatsFuns C:\Users\...
There were many instances of this warning. Also, 'lbeta' is deprecated and now `logabsbeta'.
All ok: Testing Distributions tests passed. 

(v1.2) pkg> up Knet
 - Knet v1.2.5
(v1.2) pkg> build Knet
(v1.2) pkg> test Knet
424.761536 seconds (87.54 M allocations: 3.195 GiB, 44.22% gc time)
   Testing Knet tests passed

The CUDAapi package and commands were helpful in the process:
# # using Pkg; Pkg.add("CUDAapi")
using CUDAapi
find_host_compiler()
tk=find_toolkit()
find_cuda_library("cudart",tk)
find_cuda_library("cudnn",tk)

**Comment by ViralBShah** [comment]
@denizyuret Is this still an issue?

**Comment by denizyuret** [comment]
I don't think so, it was a temporary issue where SpecialFunctions could not
be updated due to package conflicts.
