### ISSUE TITLE
SpecialFunctions 0.8.0 Build freezes on Julia 1.2

### ISSUE THREAD

**Issue by Red-Portal** [JuliaMath/SpecialFunctions.jl#190]
For some reason building `SpecialFunctions 0.8.0` doesn't end for more than 10 minutes.
The build.log file is empty.
downgrading to 0.7.2 solved the issue.

**Comment by ararslan** [comment]
Do you mean it freezes on 1.3? You said it freezes on 1.2 but that downgrading _to_ 1.2 fixes it.

**Comment by ararslan** [comment]
Also can you provide your `versioninfo()`?

**Comment by Red-Portal** [comment]
My bad, that's a ridiculous typo. I fixed the issue.

**Comment by Red-Portal** [comment]
```
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```
Here's the versioninfo.

**Comment by giordano** [comment]
Have you tried to build again 0.8.0?  Since building consists of downloading a tarball there might have been the possibility that you had temporary connection problems

**Comment by ararslan** [comment]
You can also uninstall and reinstall the package to try to retrigger a clean build.

**Comment by Red-Portal** [comment]
I tried all that you guys suggested but nothing worked unfortunately.

**Comment by musm** [comment]
stale. Please reopen if still encountering issues.
