### ISSUE TITLE
Definition of erf in help is incorrect

### ISSUE THREAD

**Issue by rstockerstat** [JuliaMath/SpecialFunctions.jl#198]
When using the help mode of the REPL it produced the following definition for the erf function.

erf(x)

  Compute the error function of x, defined by

\operatorname{erf}(x) = \frac{2}{\pi} \int_0^x \exp(-t^2) \; \mathrm{d}t
\quad \text{for} \quad x \in \mathbb{C} \, .

Should the fraction be \frac{2}{\sqrt{\pi}}?  (Is the square root missing?)

**Comment by simonbyrne** [comment]
Yes, I think you're right. Care to make a pull request?

**Comment by stevengj** [comment]
Already fixed in #195
