### ISSUE TITLE
Data for Readme.md, Licence and Subtitle.

### ISSUE THREAD

**Issue by mschauer** [JuliaMath/SpecialFunctions.jl#2]
The original readme for AMOS, part of Netlib, was:

> A Portable Package for Bessel Functions of a Complex Argument
>  and Nonnegative Order
> 
> This algorithm is a package of subroutines for computing Bessel
>  functions and Airy functions.  The routines are updated
>  versions of those routines found in TOMS algorithm 644.

As far as I understand these are semi-automated fortran-julia translations, and the Wiki statement "_The code base of Netlib was written at a time when computer software was not yet considered a merchandise. Therefore, no license terms or terms of use are stated for many programs._" applies. Does anybody have the link to the translation script? Also: "This algorithm is a package of subroutines"... Hm? ;-)

Subtitle:

Julia implementations of Bessel and Airy functions 

Summary:

Port of the Netlib package AMOS. AMOS, "A portable package for Bessel Functions of a Complex Argument and Nonnegative Order" contains subroutines for computing Bessel functions and Airy functions in Fortran. The code was translated to Julia using a semi-automated process.

**Comment by ararslan** [comment]
If I'm not mistaken, the conversion is done via [src/pass0.sh](https://github.com/JuliaMath/SpecialFunctions.jl/blob/master/src/amos/pass0.sh) and [src/pass1.jl](https://github.com/JuliaMath/SpecialFunctions.jl/blob/master/src/amos/pass1.jl).

I've been wondering if we could get better performance by hand-writing the Julia code in a more idiomatic way. The translation process is pretty genious but the generated Julia code is a little scary. (IMHO)

**Comment by ararslan** [comment]
To address the rest of your comment, I think as it stands your proposed text is great. Though if we do decide to rewrite the Julia code then we'd want to modify the summary accordingly.

**Comment by tkelman** [comment]
I think there's some history in some old Julia/openspecfun/openlibm (early on openspecfun was part of openlibm) issues of someone tracking down the actual license for the AMOS code.

**Comment by mschauer** [comment]
Had a look and couldn't find it yet, but the Fortran code was public domain anyway

**Comment by ararslan** [comment]
Closing as partially implemented, partially not relevant (current master does not use the translation script)
