### ISSUE TITLE
Add log_erfc

### ISSUE THREAD

**Issue by cossio** [JuliaMath/SpecialFunctions.jl#202]
Consider adding the function `log_erfc(x) = log(erfc(x))`, but computed in a numerically stable way.

An implementation in C can be found in the GSL, https://github.com/ampl/gsl/blob/644e768630841bd085cb7121085a688c4ff424d0/specfunc/erfc.c.
This can serve as inspiration at least, but I'm not sure we can port it directly due to the GNU license?

**Comment by stevengj** [comment]
You can always use `erfcx` for this...

**Comment by cossio** [comment]
Sorry for digressing, but how about computing `log(erfcx(x))`? I was thinking I could use ` = x^2 + log_erfc(x)`. You suggest that just `log(erfcx(x))` would be better?

**Comment by cossio** [comment]
The implementation in GSL is specialized to Float64. Would be nice to generalize this to other floats.

**Comment by simonbyrne** [comment]
One was added in #194.
