### ISSUE TITLE
function naming style guide

### ISSUE THREAD

**Issue by PaulXiCao** [JuliaMath/SpecialFunctions.jl#217]
The argument came up a couple of times already and I think it should be discussed once and for all in a separate issue here.

**How should we name functions?** 

For example _Hermite polynomials_ could possibly be named as 

- <code>hermiteh</code>
- <code>hermiteH</code>
- <code>hermite_h</code>
- ...

First question: Should we be strict and name all functions in this package following one style guide, no matter what? Or rather trying to follow one style guide but leave room for other possibilities.

Second Q: Which style guide to favour? 
I can list some possibilities:

- [julia convention](https://docs.julialang.org/en/v1/manual/style-guide/index.html): favours <code>hermiteh</code> over <code>hermite_h</code> and disallows <code>hermiteH</code>
> functions are lowercase (maximum, convert) and, when readable, with multiple words squashed together (isequal, haskey). When necessary, use underscores as word separators. Underscores are also used to indicate a combination of concepts (remotecall_fetch as a more efficient implementation of fetch(remotecall(...))) or as modifiers.

- following other vendors/libraries
  - [scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.hermite.html) <code>hermite</code>
  - [MATLAB](https://www.mathworks.com/help/symbolic/hermiteh.html) <code>hermiteH</code>
  - [mathematica](https://reference.wolfram.com/language/ref/HermiteH.html) <code>HermiteH</code>

**Comment by ararslan** [comment]
I'd say just use best judgement and follow Base where it makes sense to do so without making things confusing to read. In this case I would personally favor `hermite_h`, but so long as it isn't `hermiteH`, I think it's fine.
