### ISSUE TITLE
Ship v.11 to Julia registry?

### ISSUE THREAD

**Issue by chelate** [JuliaMath/SpecialFunctions.jl#220]
I load the package but there are missing functions, including the just added sphericalbesselj... absolutely no idea why.

```
julia> using SpecialFunctions

julia> sphericalbesselj
ERROR: UndefVarError: sphericalbesselj not defined
```

**Comment by chelate** [comment]
The package manager is refusing to update because of some requirements from ColorVectorSpace

**Comment by chelate** [comment]
Could someone please make a new release, so that other packages project.toml files know about the v.11 Bessel functions?

**Comment by ararslan** [comment]
https://github.com/JuliaRegistries/General/pull/14696
