### ISSUE TITLE
Does the next release need to be breaking?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaMath/SpecialFunctions.jl#221]
The latest stable release is 0.10.0.

The version number on master is 0.11.0.

However, when I look at the list of commits made to master since 0.10.0, it's not immediately obvious to me that any of those commits introduced a breaking change to the stable public API.

Have there been any breaking changes merged into master sine 0.10.0?

If not, then the next release should be 0.10.1, not 0.11.0.

**Comment by DilumAluthge** [comment]
This was the pull request that bumped the version number from 0.10.0 to 0.11.0: https://github.com/JuliaMath/SpecialFunctions.jl/pull/196

What was breaking in that pull request? I don't think new exports are considered breaking.

**Comment by ararslan** [comment]
Fixed version number, newest tag is 0.10.1 https://github.com/JuliaRegistries/General/pull/14696
