### ISSUE TITLE
Confusing MethodError message

### ISSUE THREAD

**Issue by knuesel** [JuliaMath/SpecialFunctions.jl#228]
The error shown by `zeta` for unsupported number types is confusing:

```julia
julia> using Measurements

julia> zeta(2.0 ± 0.1)
ERROR: MethodError: no method matching zeta(::Measurement{Float64})
Closest candidates are:
  zeta(::Number) at /home/user/.julia/packages/SpecialFunctions/Bdhxh/src/gamma.jl:527
  zeta(::Number, ::Number) at /home/user/.julia/packages/SpecialFunctions/Bdhxh/src/gamma.jl:547
  zeta(::BigFloat) at /home/user/.julia/packages/SpecialFunctions/Bdhxh/src/gamma.jl:465
  ...
```

It's confusing since there is a candidate `zeta(::Number)` and

```julia
julia> Measurement{Float64} <: Number
true
```

**Comment by giordano** [comment]
Well, the method you mentioned throws a `MethodError`: https://github.com/JuliaMath/SpecialFunctions.jl/blob/fc960c66e56d230a83999d8fa76c2c5bba28441c/src/gamma.jl#L526-L531

The case of the `zeta` function is explicitly mentioned in [the documentation of](https://juliaphysics.github.io/Measurements.jl/stable/examples/#@uncertain-Macro-1) `Measurements.jl`:
```julia
julia> using Measurements, SpecialFunctions

julia> @uncertain zeta(2.0 ± 0.1)
1.645 ± 0.094
```

**Comment by knuesel** [comment]
Indeed... Maybe it should throw an ArgumentError instead, with an informative message? Or maybe it's an issue with MethodError itself ([discussion on Discourse](https://discourse.julialang.org/t/confusing-methoderror-bad-message-or-bad-usage/39528)).

**Comment by devmotion** [comment]
The confusing MethodError was fixed by https://github.com/JuliaMath/SpecialFunctions.jl/pull/347. Instead of throwing a MethodError manually now `zeta(::Number)` calls an internal function `SpecialFunctions._zeta` which uses regular dispatching. With SpecialFunctions 1.7.0:
```julia
julia> using Measurements, SpecialFunctions

julia> zeta(2.0 ± 0.1)
ERROR: MethodError: no method matching _zeta(::Measurement{Float64})
Closest candidates are:
  _zeta(::Union{Float64, ComplexF64}) at /home/david/.julia/packages/SpecialFunctions/5CocL/src/gamma.jl:414
  _zeta(::T, ::T) where T<:Union{Float64, ComplexF64} at /home/david/.julia/packages/SpecialFunctions/5CocL/src/gamma.jl:233
  _zeta(::BigFloat) at /home/david/.julia/packages/SpecialFunctions/5CocL/src/gamma.jl:473
  ...
Stacktrace:
 [1] zeta(s::Measurement{Float64})
   @ SpecialFunctions ~/.julia/packages/SpecialFunctions/5CocL/src/gamma.jl:412
 [2] top-level scope
   @ REPL[4]:1
```

**Comment by knuesel** [comment]
Indeed that fixes it, thanks!
