### ISSUE TITLE
Gamma with Complex{BigFloat} throws StackOverflowError:

### ISSUE THREAD

**Issue by HumpyBlumpy** [JuliaMath/SpecialFunctions.jl#233]
Example:
`gamma(big(5.0+1im))`

gives 
```
StackOverflowError:

Stacktrace:
 [1] loggamma(::Complex{BigFloat}) at /home/.julia/packages/SpecialFunctions/LC8dm/src/gamma.jl:669 (repeats 79984 times)
```

**Comment by stevengj** [comment]
Basically, this should be a `MethodError`, but because of how the fallbacks are implemented you get a `StackOverflowError` instead.

**Comment by HumpyBlumpy** [comment]
Why?
So is it impossible to use big complex numbers ?
Is there no other solution?

**Comment by stevengj** [comment]
Nope, that is not currently implemented.
