### ISSUE TITLE
expint requires Julia 1.4 for evalpoly

### ISSUE THREAD

**Issue by stevengj** [JuliaMath/SpecialFunctions.jl#251]
The current implementation uses the `evalpoly` function, which requires Julia 1.4.  Three options:

1. Change it to use `@evalpoly`
2. Bump the Julia requirement to 1.4 in Project.toml
3. Use `Compat.evalpoly`, which adds a dependency on the Compat package.

My inclination is (1), since I don't think the [three lines where `evalpoly` is used](https://github.com/JuliaMath/SpecialFunctions.jl/blob/1549f9815f7e975958a0488f1f874918b251e85d/src/expint.jl#L121-L123) will be that much worse if we simply paste in the constants and use `@evalpoly`.

cc @augustt198

**Comment by ararslan** [comment]
Also +1 for option 1, +0.5 for option 2.
