### ISSUE TITLE
Documentation missing for latest tags

### ISSUE THREAD

**Issue by roflmaostc** [JuliaMath/SpecialFunctions.jl#286]
The documentation stopped being published for new tagged versions > v0.10.
See [here](https://juliamath.github.io/SpecialFunctions.jl/v0.10/)

The latest [dev doc](https://juliamath.github.io/SpecialFunctions.jl/dev/) seem to match the latest releases.
But the latest [stable doc](https://juliamath.github.io/SpecialFunctions.jl/stable/) points to something outdated.

In the `gh-pages` branch there is [no folder for the latest versions](https://github.com/JuliaMath/SpecialFunctions.jl/tree/gh-pages).

Do you know what's going on?

Thanks,

Felix

**Comment by stevengj** [comment]
@giordano, I thought this got fixed in #252?

**Comment by giordano** [comment]
It looks like I missed to add the keys to TagBot (by default actions cannot trigger other actions....)

**Comment by stevengj** [comment]
Should be fixed on the next tag now that #287 is merged?

**Comment by giordano** [comment]
Yes.  If you want to get the missing documentation versions, I think you need to delete the corresponding tags and recreate them
