### ISSUE TITLE
hankelh1(n,0.0)

### ISSUE THREAD

**Issue by KristofferC** [JuliaMath/SpecialFunctions.jl#29]
Moved from https://github.com/JuliaLang/julia/issues/18698

----------

According to the resolution of Issue #6564,
`hankelh1(1, 0.0::Real)`
should return something along the lines `0.0-1im*Inf`.

Instead, an AmosException is thrown:

```
julia> hankelh1(1,0.0) 
ERROR: Base.Math.AmosException(1)
 in _besselh at ./special/bessel.jl:128
 in besselh at ./special/bessel.jl:195
```

Is this the intended behavior of the function?

Thank you for your time.

(I'm using julia-0.4.)

**Comment by simonbyrne** [comment]
Fixed by #200.
