### ISSUE TITLE
Derivatives of Bessel functions with respect to the order

### ISSUE THREAD

**Issue by oxinabox** [JuliaMath/SpecialFunctions.jl#292]
Transefering from https://github.com/JuliaDiff/ChainRules.jl/issues/208
more details in that thread.

@devmotion  said:

>In https://www.tandfonline.com/doi/pdf/10.1080/10652469.2016.1164156, closed-form expressions were derived for the derivatives of Bessel functions with respect to the order. Currently these are not implemented (they are defined as NaN). These derivatives are useful, e.g., when working with the Matern kernel (see JuliaGaussianProcesses/KernelFunctions.jl#116 (comment)).

> It feels a bit problematic that these expressions involve hypergeometric functions and hence probably would introduce a dependency on HypergeometricFunctions.jl. Before putting together any PRs, I would like to know what's the preferred way in ChainRules to deal with such dependencies that are only needed for computing the derivatives? I assume as well that maybe one should use the @thunk macro to avoid these rather lengthy calculations if one is not interested in the derivatives with respect to the order?

NB: they are now defines as a thunked error.
Not having these causes problems for an AD that unthunked everything, including things that are not consumed.
Which is not an ideal behavour, but it is the behavour of Zygote for now (hopefully will change soon)  FluxML/Zygote.jl#873.
but more significantly, not having these means we can't take deriviative with respect to this.

**Comment by devmotion** [comment]
Possible duplicate: https://github.com/JuliaMath/SpecialFunctions.jl/issues/160

**Comment by oxinabox** [comment]
confirmed duplicate
