### ISSUE TITLE
renaming factorial 

### ISSUE THREAD

**Issue by PaulXiCao** [JuliaMath/SpecialFunctions.jl#296]
`Base.factorial` is extended in SpecialFunction.jl (the actual code is [here](https://github.com/JuliaMath/SpecialFunctions.jl/blob/281292fffb97d922b2597ae570d36b061792cac9/src/gamma.jl#L887)). 

This is _type piracy_ and doesn't follow [Julia's style guide](https://docs.julialang.org/en/v1/manual/style-guide/#Avoid-type-piracy).

There is at least one problem with it for which we did not find a solution so far:
The method [`Base.factorial(x::BigFloat)`](https://github.com/JuliaLang/julia/blob/68133407404f3e1221385d495b47eb8585b258af/base/mpfr.jl#L640) assumes `x::UInt` and therefor, we cannot overwrite it using the `gamma` function for arbitrary `BigFloat`s. There is also an issue #233 for it.

Why don't we just define our own factorial function? 
We would need a name for it. What about `fact`?
This could be a possible implementation:
```
fact(x) = gamma(x + 1)
fact(x::Integer) = Base.factorial(x) # fallback for x Integer
```

**Comment by stevengj** [comment]
It’s not clear to me that we should extend/define factorial at all, since for non-integer inputs one rarely calls the Gamma function a “factorial”

**Comment by PaulXiCao** [comment]
Even better! I will propose a pr to remove the factorial implementation in here.
