### ISSUE TITLE
maclaurin series using recursion

### ISSUE THREAD

**Issue by kumardivakar** [JuliaMath/SpecialFunctions.jl#298]
[sinx.txt](https://github.com/JuliaMath/SpecialFunctions.jl/files/5860053/sinx.txt)
It's not giving desired output.

**Comment by PaulXiCao** [comment]
Please elaborate. What does not give the desired output and what is your file suppose to show?

**Comment by kumardivakar** [comment]
i have used recursion approach to find the value of maclaurin series (sin x) ,..
[sinx (1).txt](https://github.com/JuliaMath/SpecialFunctions.jl/files/5878942/sinx.1.txt)

**Comment by PaulXiCao** [comment]
Are you sure to be on the right platform? This is a github repository about a [Julia](https://julialang.org/) programming language's library called SpecialFunctions.jl. Your question might be better placed at [stackoverflow.com](https://stackoverflow.com/) or something similar.
