### ISSUE TITLE
Julia 1.6 in Windows 10 installs old version

### ISSUE THREAD

**Issue by IgnacioRubioScola** [JuliaMath/SpecialFunctions.jl#306]
Hi,
On Windows 10 and with Julia 1.6, doing:
`] add SpecialFunctions`
or
`using Pkg; Pkg.add("SpecialFunctions")`
installs an old version:
> [276daf66] SpecialFunctions v0.10.3

How can I install latest version (1.3.0)?
Thank you,
Ignacio

**Comment by stevengj** [comment]
Probably you have some other package that currently requires an old version of SpecialFunctions.  You can try doing:
```
pkg> add SpecialFunctions@1.3.0
```
at the pkg prompt (type `]` in the REPL) and see what package complains.
