### ISSUE TITLE
Sine and cosine integrals

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaMath/SpecialFunctions.jl#31]
These are reasonably common special functions and similar to the family of exponential integrals #19. I'm happy to import a double precision implementation from [here](https://github.com/MikaelSlevinsky/SincFun.jl/blob/master/src/sinc.jl), based on McLeod's rational minimax Chebyshev approximations.

Matlab's naming convention is `sinint` and `cosint`. Is this an issue?

**Comment by ararslan** [comment]
That functionality sounds useful. As for the name, the `int` on the end could be a little confusing given that we have a proper `Int` type (Matlab does not, IIRC?) so one might assume `sinint` is equivalent to `sin(x::Int)` or `trunc(Int, sin(x))`. Perhaps a more descriptive name is in order, though I don't have any suggestions off the top of my head. @stevengj might.

**Comment by stevengj** [comment]
`expint` or `expi` seem to be common names for exponential integrals, so `sinint` seems fine to me.

**Comment by ararslan** [comment]
Okay, that's fine then. A PR would be welcome, @MikaelSlevinsky!
