### ISSUE TITLE
endless loop in gamma_inc?

### ISSUE THREAD

**Issue by mehdibida** [JuliaMath/SpecialFunctions.jl#311]
The gamma_inc function gets stuck for some of the values I tested, for example :
```
gamma_inc(29.0, 0.3, 0)
```
It doesn't work either if I change `IND` to `1` or `2`.

Julia version: 1.6, SpecialFunctions version: 1.3.0

**Comment by wulpuqu** [comment]
Same problem for `gamma_inc(100,0.1)` ! Could it be possible to have a maximum number of iterations ?

**Comment by andreasnoack** [comment]
I just compared with the old NSWC Fortran source that the implementation here is based on and there is an `else` branch missing in https://github.com/JuliaMath/SpecialFunctions.jl/blob/85ac912e871edbae2cc23345f100ddcf3b5de41a/src/gamma_inc.jl#L840 so the function continues to https://github.com/JuliaMath/SpecialFunctions.jl/blob/85ac912e871edbae2cc23345f100ddcf3b5de41a/src/gamma_inc.jl#L871-L876 but the continued fraction evaluation is not appropriate here. These arguments are supposed to be evaluated with a Taylor series. The missing else branch should be similar to https://github.com/JuliaMath/SpecialFunctions.jl/blob/85ac912e871edbae2cc23345f100ddcf3b5de41a/src/gamma_inc.jl#L842-L860. The Fortran source uses a lot of GOTOs which are a bit tricky translate into pure if/else statements.
