### ISSUE TITLE
Derivatives of exponential integrals

### ISSUE THREAD

**Issue by oxinabox** [JuliaMath/SpecialFunctions.jl#321]
Moving this from https://github.com/JuliaDiff/ChainRules.jl/issues/292 since the code now lives here.

@stevengj  said:

> Just added to SpecialFunctions.jl: JuliaMath/SpecialFunctions.jl#236
>
> The derivative with respect to x is a simple recurrence: https://en.wikipedia.org/wiki/Exponential_integral#Derivatives

**Comment by stevengj** [comment]
Closing based on #328.   (Derivatives with respect to the order aren't going to happen for a long time, if ever…)

**Comment by giordano** [comment]
> Derivatives with respect to the order aren't going to happen for a long time

Out of curiosity, what'd be the meaning of the derivative with respect to a discrete parameter? How one would go about that? By extending the domain from N to R?

**Comment by stevengj** [comment]
> Out of curiosity, what'd be the meaning of the derivative with respect to a discrete parameter? How one would go about that? By extending the domain from N to R?

It's not a discrete parameter.   It supports arbitrary complex order:
```jl
julia> expint(1.01, 3)
0.01301964756083072

julia> expint(1.01+0.4im, 3)
0.012931671071467582 - 0.0011410591248868325im
```

**Comment by giordano** [comment]
Oh, ok, I didn't check, but the name "order" made me think it was a discrete order.  Thanks!
