### ISSUE TITLE
besseli(n, 0) with n negative

### ISSUE THREAD

**Issue by matthew-wingate** [JuliaMath/SpecialFunctions.jl#33]
Calling `besseli(nu, 0)` with nu < 0 raises an exception: `SpecialFunctions.AmosException(1)`. This is correct for non-integer nu, but `besseli(nu, 0)` should return 0 for integer nu (except nu=0). The problem is caused by the call to `besselk(nu, 0)` which is divergent.  Can the term `2_besselk(-nu,z,Int32(1))*sinpi(nu)/pi` be set to 0 for integer nu to avoid this exception? Cheers!

**Comment by stevengj** [comment]
Yes, we could check for that case.

**Comment by ararslan** [comment]
If you'd be willing to submit a PR that'd be great!

**Comment by musm** [comment]
closed by https://github.com/JuliaMath/SpecialFunctions.jl/pull/34
