### ISSUE TITLE
another gamma_inc endless loop

### ISSUE THREAD

**Issue by mmattocks** [JuliaMath/SpecialFunctions.jl#341]
I think I found another case like #311.

`gamma_inc(166,99,0)` does not terminate. Possibly, the "elseif" at gamma_inc.jl line 895 should not be exclusive. Changing this to a second "if" statement at least seems to return the correct results.

**Comment by andreasnoack** [comment]
This seems to be working now
```julia
julia> StatsFuns.gamma_inc(166,99,0)
(5.13948895764429e-10, 0.9999999994860511)
```
