### ISSUE TITLE
besselj(-55, Complex128(1.0e-4, 0.0)) throws AmosException(2)

### ISSUE THREAD

**Issue by jwscook** [JuliaMath/SpecialFunctions.jl#35]
On Julia 0.6 commit `commit b70b52b4f4685ca9859d6b3e4bd1a377406ad1cc (tag: v0.1.0)` I'm experiencing the following behaviour:

`besselj(-55, Complex128(1.0e-4, 0.0))` will throw `AmosException(2)`

Since `besselj(-55, 1.0e-4)` does not throw an error, I assume that there is a bug for the Complex case?

**Comment by matthew-wingate** [comment]
This is similar to issue #33 and should be fixed by pull request #34.

**Comment by musm** [comment]
closed by https://github.com/JuliaMath/SpecialFunctions.jl/issues/35
