### ISSUE TITLE
Deprecation of factorial(::Number) (backport)

### ISSUE THREAD

**Issue by oxinabox** [JuliaMath/SpecialFunctions.jl#366]
It would be good (to go with #364 ) to have a 1.x release that include the deprecation for `factorial(::Number)`, which was removed in https://github.com/JuliaMath/SpecialFunctions.jl/pull/297

**Comment by ararslan** [comment]
There is now a `release-1.8` branch from which 1.8.x releases are made that contain bugfixes landed on `master`.
