### ISSUE TITLE
1476 Broken Chain Rules

### ISSUE THREAD

**Issue by iajzenszmi** [JuliaMath/SpecialFunctions.jl#367]
ian@ian-Aspire-One-753:~/juliaspecialfunctions/SpecialFunctions.jl/test$ ~/julia/julia-1.7.0-rc2/./julia runtests.jl
Test Summary: | Pass  Total
bessel        |  584    584
Test Summary: | Pass  Total
beta_inc      |  935    935
Test Summary: | Pass  Total
betanc        |   25     25
Test Summary: | Pass  Total
ellip         |   36     36
Test Summary: | Pass  Total
erf           |  472    472
Test Summary: | Pass  Broken  Total
expint        | 6351       1   6352
Test Summary: | Pass  Total
gamma_inc     | 1743   1743
Test Summary: | Pass  Total
gamma         |  453    453
Test Summary: | Pass  Total
sincosint     |   82     82
Test Summary: | Pass  Total
other_tests   |  110    110
Test Summary: | Pass  Broken  Total
chainrules    | 7293    1476   8769
ian@ian-Aspire-One-753:~/juliaspecialfunctions/SpecialFunctions.jl/test$

**Comment by stevengj** [comment]
Not clear what the issue is?   CI tests are currently passing…

**Comment by stevengj** [comment]
The "broken" tests reported correspond to derivatives that are not implemented, like this one: https://github.com/JuliaMath/SpecialFunctions.jl/blob/ebe328f46e93b95ae8c903e3b7a3a94d6886faae/src/chainrules.jl#L52

**Comment by iajzenszmi** [comment]
The broken tests reporting could be edited to include information about
derivatives that are not implemented.

**Comment by stevengj** [comment]
Maybe, but that is an issue for the https://github.com/JuliaDiff/ChainRulesTestUtils.jl repo
