### ISSUE TITLE
expint definition in help text is wrong

### ISSUE THREAD

**Issue by costabel** [JuliaMath/SpecialFunctions.jl#368]
expint.jl, line 511 is
Computes the exponential integral ``\\operatorname{E}_\\nu(z) = \\int_0^\\infty \\frac{e^{-zt}}{t^\\nu} dt``.
Lower limit 0 of integral is wrong, should be 1:
Computes the exponential integral ``\\operatorname{E}_\\nu(z) = \\int_1^\\infty \\frac{e^{-zt}}{t^\\nu} dt``.

Compare the references given, e.g. <https://dlmf.nist.gov/8.19#i>

Same error line 523, help text for expintx.

**Comment by stevengj** [comment]
Thanks, should be fixed now.
