### ISSUE TITLE
Vectorization depwarns accidentally export functions

### ISSUE THREAD

**Issue by carlobaldassi** [JuliaMath/SpecialFunctions.jl#37]
Despite the [check of the julia version](https://github.com/JuliaMath/SpecialFunctions.jl/blob/48429728a02828466b86feac267c88d85480ffbf/src/SpecialFunctions.jl#L7) on the `export` statement in SpecialFunctions.jl, the [vectorization deprecation warnings](https://github.com/JuliaMath/SpecialFunctions.jl/blob/48429728a02828466b86feac267c88d85480ffbf/src/deprecated.jl#L8) still export some functions.

Example: on julia 0.5:

```
julia-0.5> using SpecialFunctions

julia-0.5> erf
WARNING: both SpecialFunctions and Base export "erf"; uses of it in module Main must be qualified
ERROR: UndefVarError: erf not defined
```

Of course, this breaks compatibility in code that is supposed to work on julia 0.5 and later.

**Comment by carlobaldassi** [comment]
Just for completeness, a solution for now is a very ugly conditional import:
```
VERSION >= v"0.6.0-dev.2767" && using SpecialFunctions
```

**Comment by ararslan** [comment]
Can we just delete the deprecations at this point and assume that people will use dot-broadcast for vectorization? I'd be willing to bet that people are already familiar with doing that anyway.

**Comment by devmotion** [comment]
The deprecations were removed in https://github.com/JuliaMath/SpecialFunctions.jl/pull/39.
