### ISSUE TITLE
Can't install this package 

### ISSUE THREAD

**Issue by niravmehtax** [JuliaMath/SpecialFunctions.jl#405]
Hello! I have an M1 macbook and cannot install this package when using Julia 1.8.0 beta 3. (I thought this was the appropriate place to post this. Sorry if that's not right!)

Here's the error message I received:
ERROR: Error building `SpecialFunctions`: 
             ┌ Warning: Platform `arm64-apple-darwin21.3.0` is not an officially supported platform
             └ @ BinaryProvider ~/.julia/packages/BinaryProvider/U2dKK/src/PlatformNames.jl:450

**Comment by ararslan** [comment]
I can't reproduce this issue. What version of the package are you trying to install? Given that the warning is emitted by BinaryProvider, which hasn't been used by this package since version 0.9 (circa 2019), I suspect that your registry and/or environment is outdated. I'd recommend doing `]update` and retrying.

**Comment by giordano** [comment]
> I'd recommend doing ]update and retrying.

Or, if that doesn't help, try running `]add SpecialFunctions@2.1.7` to force installation of the latest version of this package, and see what's holding it back.

**Comment by niravmehtax** [comment]
Thanks. 
> > I'd recommend doing ]update and retrying.

I tried ]update and got the following:
(@v1.8) pkg> add SpecialFunctions
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`
But when I tried to use SpecialFunctions, it complained that it hadn't been installed properly, and that I try Pkg.build("SpecialFunctions"), restart, and try again. I did this, and it said it failed to precompile SpecialFunctions. 

Side note: I am not sure how to check which version of the package I'm trying to install; I'm not specifying it so it must be the default. Here is my output of ]status:
(@v1.8) pkg> status
Status `~/.julia/environments/v1.8/Project.toml`
  [c52e3926] Atom v0.12.38
  [6e4b80f9] BenchmarkTools v1.3.1
⌃ [a134a8b2] BlackBoxOptim v0.5.0
  [336ed68f] CSV v0.10.4
  [159f3aea] Cairo v1.0.5
⌅ [324d7699] CategoricalArrays v0.8.3
  [a93c6f00] DataFrames v1.3.4
⌅ [31c24e10] Distributions v0.23.8
⌃ [4d6a76a9] Econometrics v0.2.7
⌃ [9d5cd8c9] FixedEffectModels v1.6.3
  [186bb1d3] Fontconfig v0.4.0
  [f6369f11] ForwardDiff v0.10.30
  [38e38edf] GLM v1.8.0
  [c91e804a] Gadfly v1.3.4
  [92d709cd] IrrationalConstants v0.1.1
  [033835bb] JLD2 v0.4.22
  [4076af6c] JuMP v1.1.1
  [e5e0dc1b] Juno v0.8.4
  [67920dd8] KNITRO v0.13.0
⌃ [add582a8] MLJ v0.16.5
⌅ [e1d29d7a] Missings v0.4.5
  [ff71e718] MixedModels v4.6.4
  [76087f3c] NLopt v0.6.5
  [2774e3e8] NLsolve v4.5.1
  [86f7a689] NamedArrays v0.9.6
⌅ [429524aa] Optim v0.21.0
  [d96e819e] Parameters v0.12.3
  [91a5bcdd] Plots v1.31.1
  [6f49c342] RCall v0.13.13
  [df47a6cb] RData v0.8.3
  [d519eb52] RegressionTables v0.5.4
⌅ [276daf66] SpecialFunctions v0.8.0
  [f27f6e37] libvorbis_jll v1.3.7+1
  [dfaa095f] x265_jll v3.5.0+0
  [37e2e46d] LinearAlgebra
  [9a3f8284] Random

> Or, if that doesn't help, try running `]add SpecialFunctions@2.1.7` to force installation of the latest version of this package, and see what's holding it back.

When I tried this I got the following output:
(@v1.8) pkg> add SpecialFunctions@2.1.7
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Distributions [31c24e10]:
 Distributions [31c24e10] log:
 ├─possible versions are: 0.16.0-0.25.64 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.16.0-0.25.64
 ├─restricted by compatibility requirements with SpecialFunctions [276daf66] to versions: 0.25.36-0.25.64 or uninstalled, leaving only versions: 0.25.36-0.25.64
 │ └─SpecialFunctions [276daf66] log:
 │   ├─possible versions are: 0.7.0-2.1.7 or uninstalled
 │   └─restricted to versions 2.1.7 by an explicit requirement, leaving only versions 2.1.7
 └─restricted by compatibility requirements with Econometrics [4d6a76a9] to versions: 0.16.0-0.24.18 — no versions left
   └─Econometrics [4d6a76a9] log:
     ├─possible versions are: 0.1.0-0.2.8 or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.2.8

**Comment by giordano** [comment]
I edited your message to make it readable by using triple backquotes for code blocks, like this:
````
```
code...
```
````

Going back to your question, this is what happens when you lots and lots of different packages in the same environment.  Do you need all of them together?  If not, I ***strongly*** suggests using local environments.

Anyway, nothing really actionable here.  Instead, you should ask [`Econometrics.jl`](https://github.com/Nosferican/Econometrics.jl) maintainers to allow more recent versions of `Distributions.jl`.  CC: @nosferican
