### ISSUE TITLE
Add Laguerre and Hermite polynomials

### ISSUE THREAD

**Issue by curio-sitas** [JuliaMath/SpecialFunctions.jl#408]
Adding [**Laguerre**](https://en.wikipedia.org/wiki/Laguerre_polynomials) and [**Hermite**](https://en.wikipedia.org/wiki/Hermite_polynomials) polynomials would enrich the package as they are useful in many fields of maths and physics.

Here are some hints on how to implement their computations : 

- [Laguerre](https://www.sciencedirect.com/science/article/abs/pii/S0010465516302727)
- [Hermite](https://www.numbercrunch.de/blog/2014/08/calculating-the-hermite-functions/)

**Comment by curio-sitas** [comment]
I am working on it, i will open a PR soon.

**Comment by stevengj** [comment]
These are already in https://github.com/jverzani/SpecialPolynomials.jl
