### ISSUE TITLE
Possible bug in gamma_inc

### ISSUE THREAD

**Issue by astrozot** [JuliaMath/SpecialFunctions.jl#418]
I believe that in the following line

https://github.com/JuliaMath/SpecialFunctions.jl/blob/36c547b4a270b6089b1baf7bec05707e9fb8c7f9/src/gamma_inc.jl#L673

`ind_` should be replaced by `ind`.

**Comment by simonbyrne** [comment]
thanks! care to open a PR?

**Comment by simonbyrne** [comment]
(PR = pull request)

**Comment by astrozot** [comment]
Sure, will do!

**Comment by astrozot** [comment]
Done, as you probably have seen already!

**Comment by ararslan** [comment]
Fixed in #419
