### ISSUE TITLE
Registering Functions with `Symbolics.jl`

### ISSUE THREAD

**Issue by cadojo** [JuliaMath/SpecialFunctions.jl#455]
An extension which registers these functions with `Symbolics.jl` would be really helpful for packages which depend on `ModelingToolkit.jl` and `Symbolics.jl`. For example, I need `gamma` and `lowergamma` function implementations for a [potential field](https://github.com/cadojo/GalacticPotentials.jl/blob/c969dd5cadc4e14c0029fd5ec1468ef02606a780/src/potentials.jl#L211) defined in [`GalacticPotentials.jl`](https://github.com/cadojo/GalacticPotentials.jl).

I am interested in working on this functionality. I will provide a draft PR soon, though I won't be able to finish this task independently for a couple of months or so. Please let me know if you agree that this functionality could belong in the `SpecialFunctions.jl` project!

**Comment by devmotion** [comment]
Ref https://github.com/JuliaMath/SpecialFunctions.jl/pull/456#issuecomment-1875553131
