### ISSUE TITLE
Conversion error during build, version 0.7

### ISSUE THREAD

**Issue by IceColdMind** [JuliaMath/SpecialFunctions.jl#67]
The error : 

    LoadError: LoadError: MethodError: Cannot `convert` an object of type Int64 to an object of type
    Symbol
    This may have arisen from a call to the constructor Symbol(...),
    since type constructors fall back to convert methods.

Files in question: `binaries.jl:37` and `build.jl:6`.

Specific version : 0.7.0-DEV.2092

**Comment by ararslan** [comment]
This was an issue in BinDeps that has since been fixed. Could you run `Pkg.update()` to ensure that you have BinDeps 0.8.1 then run `Pkg.build("SpecialFunctions")`?
