### ISSUE TITLE
Update github package desciption

### ISSUE THREAD

**Issue by oxinabox** [JuliaMath/SpecialFunctions.jl#68]
The package description currently reads:
"Julia implementations of Bessel and Airy functions"

But actually there is more than that here now.

as given in first sentence of readme:

> Special mathematical functions in Julia, including Bessel, Hankel, Airy, error, Dawson, sine and cosine integrals, eta, zeta, digamma, inverse digamma, trigamma, and polygamma functions.

**Comment by ararslan** [comment]
Set to "Special mathematical functions in Julia," as in the first sentence of the README.
