### ISSUE TITLE
erfcinv confusing error

### ISSUE THREAD

**Issue by kirtsar** [JuliaMath/SpecialFunctions.jl#78]
`Using SpecialFunctions`
`println(erfcinv(1)) # all is OK`
`println(erfcinv(BigFloat(1))) # wrong error message -- erfcinv was moved to SpecialFunctions`

The problem is that error message is confusing -- erfcinv can't handle BigFloat right now, but error message says that it is a problem of the package.

**Comment by ararslan** [comment]
Hi @kirtsar, this issue has been noted previously: https://github.com/JuliaLang/julia/issues/24618, https://github.com/JuliaMath/SpecialFunctions.jl/issues/76, so I'm going to close this issue as a duplicate. Unfortunately there isn't much we can do about this on Julia 0.6.
