### ISSUE TITLE
Connection timeout on v0.7

### ISSUE THREAD

**Issue by Roger-luo** [JuliaMath/SpecialFunctions.jl#86]
SpecialFunctions.jl fails to build on v0.7 because it cannot download libpopenspecfun-0.5.3. I fixed this myself by manually download it from github link. I'm not sure why this happens.

```julia-repl
julia> Pkg.installed("SpecialFunctions")
v"0.3.8"
```

here is my versioninfo:

```
Julia Version 0.7.0-DEV.4719
Commit 34a8068 (2018-03-29 02:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
Environment:
```

**Comment by jlapeyre** [comment]
Installation and building *does* work for me, using the Pkg3 REPL mode.

```
Julia Version 0.7.0-DEV.4810
Commit a96d847592 (2018-04-07 21:52 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```

**Comment by Roger-luo** [comment]
Works with Pkg3 thanks @jlapeyre

**Comment by Roger-luo** [comment]
Ooops, still got this error. It seems that BinDeps.jl cannot download this dependency from my side, but it works with others

**Comment by ararslan** [comment]
Can you post the full backtrace for the error?

**Comment by musm** [comment]
stale

**Comment by Roger-luo** [comment]
Yeah I think this is because of the GFW. I was inside China at that moment. I think this issue should be resolved automatically in the future with the new Pkg server.
