### ISSUE TITLE
factorial serie in c++

### ISSUE THREAD

**Issue by AriadneRos** [JuliaMath/SpecialFunctions.jl#87]
hi Julia could please help me with these problems?

	
I tried to use this in c++:                      factorial (numero)+factorial(numero-1);
I  need to print this factorial serie by using functions:  2, 3, 8, 30, 144,,  I tried but it does not work.
numero means the termin or place wich will be realized the operation, for example if numero=4 
so 4! + (4-1)! = 30 and 30 is the 4 place of the serie.

#include <iostream>
//Exercise 130.print this factorial serie by using functions in c++:  2, 3, 8, 30, 144,etc.

using std::cin;
using std::cout;
using std::endl;

unsigned long factorial(unsigned long);

int main(int argc, char** argv) {
	
	for(int i=0; i<=10; i ++)/
	cout<<i<<"!="<<factorial(i)<<endl;
	
	return 0;
}
unsigned long factorial(unsigned long numero)
{
	
	if(numero<=1)
	return 1;
	else
	return factorial (numero)+factorial(numero-1);

}

**Comment by stevengj** [comment]
This is not a C++ forum.
