### ISSUE TITLE
Use BinaryProvider

### ISSUE THREAD

**Issue by andreasnoack** [JuliaMath/SpecialFunctions.jl#95]
There is a builder at https://github.com/JuliaMath/OpenspecfunBuilder and there is a PR to update it. However, it looks like BinaryBuilder currently doesn't support Fortran for FreeBSD builds (see https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/277) so, hopefully, there will be some progress on the cross compiler soon. Please contribute there if you care about FreeBSD support otherwise we might need to drop support for FreeBSD.

**Comment by tkelman** [comment]
You also drop support for source builds of Julia on non-bleeding-edge Linux distros with existing BinaryBuilder on packages that depend on Fortran or C++. Not a good idea.

**Comment by stevengj** [comment]
See e.g. https://github.com/JuliaInterop/ZMQ.jl for an example of how to get source builds as a fallback with BinaryProvider.

**Comment by ararslan** [comment]
> Please contribute there if you care about FreeBSD support otherwise we might need to drop support for FreeBSD.

I definitely care about FreeBSD support as I use it quite frequently but I haven't had the time to debug cross compilation issues as I'm not that familiar with cross compiling in the first place. I'll see if I can find some time maybe later in the week to help, but in the meantime Steven's example seems like a good idea.

**Comment by andreasnoack** [comment]
@ararslan It appears that I was mislead by the issue linked in the top post. I've just updated to the most recent version of BinaryBuilder and FreeBSD appears to work.

**Comment by ararslan** [comment]
Great. Then using BinaryProvider seems like a good way to go here then.

**Comment by KristofferC** [comment]
https://github.com/JuliaMath/SpecialFunctions.jl/pull/96
