### ISSUE TITLE
suggestion: move log/exp combinations from StatsFuns.jl

### ISSUE THREAD

**Issue by tpapp** [JuliaMath/SpecialFunctions.jl#98]
Maybe [these functions](https://github.com/JuliaStats/StatsFuns.jl/blob/e66dd973650c375bc1739c820e5b96bb5bd000a8/src/basicfuns.jl) could be moved to SpecialFunctions.jl.

**Comment by ararslan** [comment]
What's wrong with having them in StatsFuns?

**Comment by tpapp** [comment]
While they are used in statistics (among many other fields), these functions are not *per se* statistical.

Also, because of JuliaStats/StatsFuns.jl#20, I was under the impression that that package is not for end users, while `logistic`, `softmax`, etc are useful functions on their own.

Anyway, this is just a suggestion that I thought would bring up, when revisiting the discussion for the PR above which suggested moving them to StatsBase.jl — I think SpecialFunctions.jl would be more appropriate.

**Comment by ararslan** [comment]
Yeah perhaps. (Btw, I'm not saying it's a bad suggestion, I was just wondering what your motivation was for making it. 🙂)

The plan that was discussed a while back was to move distribution-specific code in StatsFuns to Distributions, then move the rest to StatsBase. I don't have a huge preference for where functions like that end up living.

**Comment by tpapp** [comment]
Thinking about this, maybe SpecialFunctions.jl is not the right place for them either. I think they should go to their own package, and opened a discussion in JuliaStats/StatsFuns.jl#46.
